/** @format */

import type { Metadata } from "next";
import { Toaster } from "@/components/ui/toaster"
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Analytics } from "@vercel/analytics/react";

import "./globals.css";
import StoreIntializer from "@/helpers/StoreIntializer";

export const metadata: Metadata = {
  title: "The Social App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head />
      <body className="font-default">
        <StoreIntializer />
        <main>{children}</main>
        <Toaster />
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
