/** @format */

import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "The Social App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-default">{children}</body>
    </html>
  );
}
